config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :recruiters
  devise_for :candidates
  root "home#index"
  get '/signup', to: "home#signup"
  get '/signin', to: "home#signin"
  get '/about', to: "home#about", as: "/apropos"
  get '/contact', to: "home#contact"
  get '/offers', to: "home#offers"
  get '/editcv', to: "home#editcv", as: "/editermoncv"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
# frozen_string_literal: true

class Candidate < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/recruiter.rb
# frozen_string_literal: true

class Recruiter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u|
      u.permit(:first_name, :last_name, :email, :password, :password_confirmation)
    }
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def signup; end

  def signin; end

  def about; end

  def contact; end

  def offers; end

  def editcv; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/home/about.html.erb
<div class="sectionAbout">
    <div class="contentSection">
        <p><strong>Same Chances est né d'un constat simple : </strong></br></br>
        La représentation des femmes et de toutes les minorités en entrepise </br> ne sont pas à la 
        hauteur des valeurs que notre société actuelle met en avant. </p>
        <p>On prône l'égalité, la valorisation des compétences, la bienveillance... </br> 
        mais au delà des mots, Same Chances veut vous donner les moyens </br> de le réaliser afin de mettre en avant les 
        candidats pour leurs compétences </br> et leurs compétences uniquement.</p>
        <p>Ainsi les deux côtés sont gagnants, une entreprise peut trouver sa perle rare </br> 
        grâce à des critères objectifs, et les candidats sont tous mis </br> sur un même pied d'égalité.</p>
        <p>Ce projet vous parle à vous aussi ? 
        </br> Alors venez participer à l'aventure Same Chances avec nous !</p>
    </div>
</div>

app/views/home/contact.html.erb
<div class="contactSection">
    <p>contact@samechances.fr</p>
</div>

app/views/home/index.html.erb
<header class="headerHome">
    <div class="contentTopSection">
        <div class="title titleb">
            <h1 id="brand"><%= image_tag("samechances1.png", alt: "logo")%></h1>
            </br>
            <h1>Same Chances est une plateforme </br> qui met en relation des candidats ayant la possibilité de </br> créer des CVs neutres
            avec des recruteurs. </br></br> Ici pas de biais de recrutement !</h1>
        </div>

        <div class="buttons">
            <a href="#section1"><button class="buttonHome">En savoir plus pour les recruteurs</button></a>
            <a href="#section2"><button class="buttonHome">En savoir plus pour les candidats</button></a>
        </div>
    </div>
</header>
<section class="sectionOne" id="section1">
    <div class="contentSection">
        <h2 class="title">Vous êtes recruteur ?</h2>
        <div class="infosSecondSection">
            <div class="infosRecruiter container">
                <h3 class="title">Infos</h3>
                <p>Vous souhaitez recruter les meilleurs et voulait éviter les biais de jugement lors de vos futurs recrutements ?
                Same Chances vous permet d'analyser votre démographie en entreprise et de recruter vos futurs talents sur la base de critères purement objectifs.
                L'avantage ? Garder que les meilleurs éléments sur la base des compétences.</p>
            </div>
            <div class="charts container">
                <h3 class="title">Un dashboard complet sur la démographie de votre entreprise</h3>
                <%= image_tag("charts.jpg", :alt => "charts") %>
            </div>
        </div>
        <div class="buttons">
            <a href="#section2"><button class="buttonHome buttonOrange">Créer son compte entreprise</button></a>
        </div>
    </div>
</section>
<section class="sectionTwo" id="section2">
    <div class="contentSection">
        <h2 class="title">Vous êtes candidat ?</h2>
        <div class="infosSecondSection">
            <div class="charts container">
                <h3>Graphes</h3>
                <%= image_tag("charts.jpg", :alt => "charts") %>
            </div>
            <div class="infosRecruiter container">
                <h3>Infos</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ut felis mattis, finibus metus vitae, consectetur lectus. In at eleifend augue. 
                </br>Nullam dignissim nisi ac facilisis blandit. Aliquam blandit auctor tellus, eget elementum enim.</br>
                Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce interdum libero et est feugiat efficitur. Nulla convallis arcu in odio interdum dignissim. In ligula augue, tincidunt vel elit et, sodales porta risus. Nunc eu massa augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eget venenatis metus. Praesent posuere nibh dui. Duis nec ligula tincidunt, congue ante et, blandit nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi iaculis mauris suscipit tellus lobortis malesuada. Nullam iaculis rutrum nisl sit amet varius. Maecenas condimentum lacus vitae gravida cursus. 
                </br></br> Phasellus ipsum purus, tristique ut urna et, placerat faucibus magna.</p>
            </div>
        </div>
        <div class="buttons">
            <a href="#section2"><button class="buttonHome">Créer son compte candidat</button></a>
        </div>
    </div>
</section>
<section class="sectionThree">
    <div class="contentSection">
        <h2 class="title">A propos de nous</h2>
        <div class="profiles">
            <div class="profile">
                <%= image_tag("alex.jpeg", :alt => "alexandre cartier", :class => "profilePicture") %>
                <p>CEO de Same Chances, féministe avant tout. Il adore le foot et la cuisine italienne.</p>
            </div>
            <div class="profile">
                <%= image_tag("aude.png", :alt => "aude cervantes", :class => "profilePicture") %>
                <p>CMO, aime parler de sujets philosophiques et a un attrait particulier pour le plat flageolets/oeuf.</p>
            </div>
            <div class="profile">
                <%= image_tag("alexandra.jpeg", :alt => "alexandra de la gueronnière", :class => "profilePicture") %>
                <p>CTO, adore débattre et n'a pas peur d'affirmer haut et fort ses convictions, elle aime aussi tous les êtres vivants.</p>
            </div>
        </div>
        <div class="pitch">
            <p>“Same Chances veut donner les moyens à des candidats d'être recruter pour leurs compétences et leurs compétences uniquement.</p>
            <p>Tandis qu'une entreprise trouvera l'opportunité de peut-être rencontrer une perle rare qu'elle n'aurait pas eu par les moyens classiques.”</p> 
            <p>Ce projet vous parle à vous aussi ? 
            </br><strong>Alors venez participer à l'aventure Same Chances avec nous !</strong></p>
        </div>
    </div>
</section>

<% if candidate_signed_in? %>

    Il est temps de créer votre CV !

    <%= form_tag do %>
        <div class="field">
            <%= label_tag(:q, "Votre genre") %>
            <%= text_field_tag(:q) %>
            <p>Cette information ne sera pas mise en avant auprès du recruteur.</p>
        </div>

        <div class="field">
            <%= label_tag(:q, "Votre âge") %>
            <%= text_field_tag(:q) %>
            <p>Cette information ne sera pas mise en avant auprès du recruteur.</p>
        </div>

        <div class="field">
            <%= label_tag(:q, "Votre adresse") %>
            <%= text_field_tag(:q) %>
            <p>Cette information ne sera pas mise en avant auprès du recruteur.</p>
        </div>

        <div class="field">
            <%= label_tag(:q, "Votre numéro de téléphone") %>
            <%= text_field_tag(:q) %>
        </div>

        <div class="field">
            <%= label_tag(:q, "Vos expériences") %>
            <%= text_field_tag(:q) %>
        </div>

        <div class="field">
            <%= label_tag(:q, "Votre formation") %>
            <%= text_field_tag(:q) %>
        </div>

        <div class="actions">
            <%= submit_tag("Enregistrer") %>
        </div>
    <% end %>

<% end %>


<% if recruiter_signed_in? %>

    Des infos sur l'entreprise ?

    <%= form_tag do %>
        <div class="field">
            <%= label_tag(:q, "Le nom de votre entreprise") %>
            <%= text_field_tag(:q) %>
        </div>

        <div class="field">
            <%= label_tag(:q, "Description de votre entreprise") %>
            <%= text_field_tag(:q) %>
        </div>

        <div class="field">
            <%= label_tag(:q, "L'adresse de votre entreprise") %>
            <%= text_field_tag(:q) %>
        </div>

        <div class="field">
            <%= label_tag(:q, "Combien comptez-vous de femmes dans votre entreprise ?") %>
            <%= text_field_tag(:q) %>
        </div>

        <div class="field">
            <%= label_tag(:q, "Combien comptez-vous d'hommes dans votre entreprise ?") %>
            <%= text_field_tag(:q) %>
        </div>

        <div class="actions">
            <%= submit_tag("Enregistrer") %>
        </div>
    <% end %>

<% end %>

app/views/home/offers.html.erb
<div class="offersSection">
    <p>Des offres tout pleiiiiiin</p>
    <p>Les meilleures offres du monde dans les meilleures boîtes du monde !</p>
</div>

app/views/home/signin.html.erb
<p>Vous pouvez vous s'inscrire selon votre profil</p>

<button>
    <%= link_to "Se connecter en tant que candidat", new_candidate_session_path %>
</button>
<button>
    <%= link_to "Se connecter en tant que recruteur", new_recruiter_session_path %>
</button>

app/views/home/signup.html.erb
<p>Vous pouvez vous s'inscrire selon votre profil</p>

<button>
    <%= link_to "S'inscrire en tant que candidat", new_candidate_registration_path %>
</button>
<button>
    <%= link_to "S'inscrire en tant que recruteur", new_recruiter_registration_path %>
</button>

app/views/layouts/_footer.html.erb
<footer>
    <p>© 2018 Same Chances</p>
    <ul>
        <li>Termes</li>
        <li>Blog</li>
        <li><a href="/about">A propos</a></li>
        <li><a href="/about">Contact</a></li>
    </ul>
</footer>

app/views/layouts/_header.html.erb
<div class="navBar">
  <ul class="topnav">
    <li><a class="active" href="/">Same chances</a></li>
    <li><a href="/blog">Blog</a></li>
    <li><a href="/about">A propos</a></li>
    <% if candidate_signed_in? || recruiter_signed_in? %>
      <% if candidate_signed_in? %>
      <li class="right"><%= link_to "Editer mon CV", editermoncv_path %></li>
      <li class="right"><%= link_to "Voir les offres", offers_path %></li>
      <li class="right"><%= link_to "Se déconnecter", destroy_candidate_session_path, :method => :delete %></li>
      <% end %>
      <% if recruiter_signed_in? %>
      <li class="right"><a href="/mesdatas">Mon Data Dashboard</a></li>
      <li class="right"><a href="/newoffer">Créer une offre</a></li>
      <li class="right"><a href="/candidats">Liste des candidats</a></li>
      <li class="right"><a href="/dashboard_suivi">Dashboard de suivi</a></li>
      <li class="right"><%= link_to "Se déconnecter", destroy_recruiter_session_path, :method => :delete %></li>
      <% end %>
    <% else %>
    <li class="right"><a href="/signin">Se connecter</a></li>
    <li class="right"><a href="/signup">S'inscrire</a></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SameChances</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= render 'application/favicon' %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>